### PR TITLE
Introduction to GitHub Copilot

### PR DESCRIPTION
**Pull request by a-a-ron**
Tracking issue: https://github.com/githubpartners/microsoft-learn/issues/59
Skills exercise tracking issue: https://github.com/github/skills/issues/83
Outline: https://docs.google.com/document/d/1ilO96UaZyS47k1DkwANsFZIkSATn8a_q1WPc7k1FvgM/edit
Blog post: [public code detection](https://github.blog/2022-11-01-preview-referencing-public-code-in-github-copilot/)

## Outline

- What is GitHub Copilot
- How Can I Use GitHub Copilot
- Enable GitHub Copilot for Business Enterprise
- Configuring GitHub Copilot
- Troubleshooting GitHub Copilot
- Exercise (https://github.com/github/skills/issues/83)
- Knowledge Check
- Summary

### CODE REVIEW

**Comment by camihmerhar** [comment]
Howdy @rmallorybpc! Awesome job putting this together! Let me know if you have any questions. 

# Feedback on Introduction to GitHub Copilot

- Do we have an introduction for this module with the prerequisites? I think knowing that will help inform us of how we curate the content going forward.

## [1-what-is-github-copilot.md](https://github.com/githubpartners/microsoft-learn/blob/new-copilot/github/introduction-to-github-copilot/includes/1-what-is-github-copilot.md)
- In the first sentence of the unit, depending on the level of learner, should we write out Artificial Intelligence before we use the acronym?

## [2-how-to-use-github-copilot.md](https://github.com/githubpartners/microsoft-learn/blob/new-copilot/github/introduction-to-github-copilot/includes/2-how-to-use-github-copilot.md) 
- I would consider rewording the title of the unit from "How to use github copilot," to something along the lines of "Testing and Securing Code with Copilot," that way learners know what to expect with the unit.
- After the sentence "You can write a comment describing the logic you want and GitHub Copilot will immediately suggest code to implement the solution," I would add a transition sentence that introduces the sub sections. 
- I feel like the sub section "Assisting non-native English speakers" feels out of place. I feel like it might be a better fir for the 3rd learning unit, "Enable GitHub Copilot for Business Enterprise" and you can intro it with a transition sentence that states that teams can be global and that's why assisting non-native english speakers is so important.  

## [3-enable-github-copilot-for-business-enterprise.md](https://github.com/githubpartners/microsoft-learn/blob/new-copilot/github/introduction-to-github-copilot/includes/3-enable-github-copilot-for-business-enterprise.md) 
- I feel like we need an intro to this unit stating the value case for using GitHub Copilot for Business and examples of how it can help business
- For the last portion of the unit, "Enforcing a policy to manage the use of GitHub Copilot for Business in your Enterprise" in GitHub Docs... I would bullet the content afterwards to make it easier for the reader and providing images of the steps as well. 

## [4-configure-github-copilot.md](https://github.com/githubpartners/microsoft-learn/blob/new-copilot/github/introduction-to-github-copilot/includes/4-configure-github-copilot.md)
-  I feel like this needs a marketing propositional statement as to why this is important and how it relates to the following subsections and then a table of contents of the subsections at the very beginning of the unit.

### Enabling or disabling duplication detection 
- Should "An inventory of similar code found in GitHub public repositories"
be in courier font?
- Bullet out the steps to make them more digestible

### Enabling or disabling telemetry 
- "Enabling or disabling telemetry allows you to choose whether your code snippets are collected and retained by GitHub and further processed, And, shared with Microsoft and OpenAI by adjusting your user settings" lowercase A in And

### Configuring GitHub Copilot in Visual Studio Code
- After the first paragraph of this section what are your thoughts on walking through the steps of installing GH Copilot for Visual Studio?
- After the 3rd paragraph of this section I feel like a picture would go well there

### Configuring GitHub Copilot in Visual Studio
- Thoughts on an image in this section?

### Configuring ReSharper for GitHub Copilot
- I feel like we need more context here why is it best and why is this important?
- I also feel like the last sentence in the paragraph needs to be bulleted or numbered into steps.

### Configuring GitHub Copilot in a JetBrains IDE
- Do we have more information on this? I feel like this function is amazing! Are there any stats that shows how this saves people time? Also do we steps to show people how to enable this?

### Configuring GitHub Copilot in Neovim
- I think we need to dive into why this is important and how it can help someone.

## [5-troubleshoot-github-copilot.md](https://github.com/githubpartners/microsoft-learn/blob/new-copilot/github/introduction-to-github-copilot/includes/5-troubleshoot-github-copilot.md)
- I think it would be helpful to have a table of contents for the upcoming subsections in order to prep the learner for what is to come.

### Troubleshooting GitHub Copilot in Visual Studio Code
- I feel like we need to open this with something along the lines of "In Visual Studio Code the log files are useful for diagnosing connection issues." that way learners know they are in the right place.

### Troubleshooting GitHub Copilot in Visual Studio
- Because this section is so small can we combine it with the above section? If no, what are the discernible differences between the two?

## [7-summary.md](https://github.com/githubpartners/microsoft-learn/blob/new-copilot/github/introduction-to-github-copilot/includes/7-summary.md) 
- "GitHub Copilot is an AI pair programmer that suggests code in your editor." I would delete this, I feel like we already established this and it's a bit unnecessary.

**Comment by rmallorybpc** [comment]
Full review in #59

**Comment by camihmerhar** [comment]
Howdy @rmallorybpc! I hope you had a fabulous weekend! 

Here are my next round of reviews, let me know if you have any questions!

## 1-introduction.md
- Super minor but I would break up this paragraph to make it easier to read: 

"GitHub Copilot is an Artificial Intelligence (AI) pair programmer that helps you write code faster and with less work.

GitHub Copilot draws context from comments and code to suggest individual lines and whole functions instantly. 

Powered by OpenAI Codex, GitHub Copilot's generative pretrained language model is created by OpenAI. An extension is available for Visual Studio Code, Visual Studio, Neovim, and the JetBrains suite of integrated development environments (IDEs)."

- To make the content easier to digest and the module easier to navigate, I would align the learning objectives to each of the modules
- Should the prer-reqs " Introduction to GitHub" and "Introduction to GitHub" be a "A basic or intermediate level of understanding of GitHub and GitHub Administration"? Not sure what it means as of right now. 
- The transition statement at the end of the introduction sounds a bit choppy may say something like, "Next up, let's dive into learning about GitHub Copilot."

## 1-about-copilot.md 

- This unit seems a bit short, I think it might make sense to combine with the next unit. I think it also might help the flow of the module where we introduce copilot and then follow up with its functionality.

## 2-using-github-copilot.md
- I would consider rewording the title of the unit from "Using github copilot," to something along the lines of "Learning about Testing and Securing Code with Copilot," that way learners know what to expect with the unit.
- Maybe it's just me and my unfamiliarity with Copilot, but I was expecting an image or a gif of Copilot helping suggest code or testing and securing it.

### Assisting non-native English speakers
- "Importantly, GitHub Copilot can assist non-native English speakers and can understand other languages beyond English." I feel like we need a stronger transition here. Like, "We know that teams are diverse and span across the globe. That is why it was important to GitHub to add functionality to help non-native English speakers use GitHub Copilot with ease." And then remove "Importantly..." and start the next sentence as "GitHub Copilot can understand languages beyond English, helping developers of all backgrounds with program languages that are based on American English."

## 3-enable-github-copilot-for-business-enterprise.md

### Enabling GitHub Copilot for Business for your enterprise

- While revisiting the steps to manage GitHub Copilot for Business, I would break the steps out into different sections and then have the steps numbered. The different sections should be: "How to disable and enable GitHub Copilot for all Organizations" and "How to Enable GitHub Copilot Specific Organizations." I think this will make it easier for the learner to digest.
- Should "These steps are also found in: Enforcing a policy to manage the use of GitHub Copilot for Business in your enterprise” in the GitHub Docs" be linked?

## 4-configure-github-copilot.md
- I don't think you the comma in "GitHub Copilot generates new code in a probabilistic way. The models do not contain a database of code, and do not look up snippets."
- I would add in a table of contents cuing up the learner for the unit that includes the subsection in this unit. I think this will make it a bit more digestible.

### Configuring GitHub Copilot settings on GitHub.com
- Do we have steps to do this? Should we list them here?

### Enabling or disabling telemetry
- Change snipper to snippet in the following sentence, "Additionally, you can choose if your code snipper is further processed and shared with Microsoft and OpenAI by adjusting your user settings."

### Configuring ReSharper for GitHub Copilot 
- I think it might just be me, but if a title has Configuring in it, I expect step by step instructions on how to configure the tool, maybe we should rename "How ReSharper can assist GitHub Copilot"

### Configuring GitHub Copilot in a JetBrains IDE
- Similar to the above comment but for this section

###  Configuring GitHub Copilot in Neovim
- Similar to the above comment but for this section

**Comment by rmallorybpc** [comment]
Above comment moved over to #59

**Comment by a-a-ron** [comment]
This module was published. Closing out!

**Pull request closed without merging**
