### PR TITLE
New module: Manage your work on GitHub with Projects

### LINKED ISSUE #38: New module dedicated to Projects (Memex)
We need to create a dedicated module for Projects.

**Timeline: TBD**

[Projects](https://github.com/features/issues) (also known as Memex, [Issues vNext](https://thehub.github.com/initiatives/github-issues-vnext/), Projects V2, Projects Beta) is a tool for project management built directly into GitHub using [React](https://reactjs.org/).

Note: the name "Projects" is also shared by [another product of the same name](https://docs.github.com/en/issues/organizing-your-work-with-project-boards/managing-project-boards/about-project-boards), which the Memex project has now replaced, and is now called "Projects (classic)."

## Resources

- [Memex repository](https://github.com/github/memex)
- [Public documentation](https://docs.github.com/en/issues/planning-and-tracking-with-projects/learning-about-projects/about-projects)
- [Memex marketing page](https://github.com/features/issues)

### PR DESCRIPTION
**Pull request by a-a-ron**
# Module title: Manage your work on GitHub with Projects

Resolves issue https://github.com/githubpartners/microsoft-learn/issues/38

## Helpful resources
- https://docs.github.com/en/issues/planning-and-tracking-with-projects/learning-about-projects/about-projects
- [video: Building your backlog with Projects](https://www.youtube.com/watch?v=qT0VMdx7vuI)
- [video: Using Projects for feature planning](https://www.youtube.com/watch?v=yFQ-p6wMS_Y&t=79s)
- [video: Using charts with GitHub Projects](https://www.youtube.com/watch?v=Iq6uHf6oBhM)
- [Blog: On the go with GitHub Projects on GitHub Mobile](https://github.blog/2022-10-11-on-the-go-with-github-projects-on-github-mobile-public-beta/)

## Module Outline
Screen Shot 2022-10-10 at 12 30 57 PM

## Module prerequisites 

- None

## Action items for @camihmerhar 
- [x] Create module learning objectives
- [x] Create content for all MARKDOWN files
- [x] Create "narrative" flow between topics and units
- [x] 3-5 knowledge check questions written for the module and posted as a comment to this PR
- [x] Identify useful images for each learning unit

### CODE REVIEW

**Comment by a-a-ron** [comment]
Hey, @camihmerhar! First off, amazing job putting together your first module. I reviewed the content and have some feedback on some content I think we need to add. Great job with the structure and the layout.

 I'll address your slack questions first. 

## Answers to slack questions

> I tried finding a skills exercise to go along with the module, but I couldn’t find one that fit the 101 level I was trying to achieve with the module. What are your thoughts on me creating an exercise for this module? Or another option is to preface in the Intro to work alongside the module?

We don't have a hands-on exercises to use at the moment. For now, we'll publish without the exercise.

> Did I add the images correctly?

Yes, but we may need to be more descriptive with the alt text or it may be flagged by MS Learn when we try to publish it. For example, the alt text in this image syntax `:::image type="content" source="../media/example_board.png" alt-text="An Example of a Board.":::` could be more descriptive. Maybe something like, "An example of a project board with 4 columns labeled; no status, todo, in-progress, done". 

> As a person who uses projects frequently, am I missing anything that you find extremely helpful for a new user of projects?

Yes, I think we are missing a few sections. I'll provide more context below. 

> Should I include more automation content?

I would like to see some content on using the API and Actions. I don't want this to be extensive but maybe a sub section for each with about a paragraph or two talking about automating your projects using both of those options.

> What am I missing from a structural perspective?

Structurally it is looking great. Files in the right place, syntax looks good, knowledge check questions added. Nice job!!

## Content I think we need to add

**Section to introduce projects and how it's different from projects (classic)**

I think this section is important and will help remove confusion on what we are referring to when we say "projects". A lot of GitHub users are familiar with projects (classic) so making sure we make this distinction clear is important. Let's add a section to the beginning of unit 2 that mentions the differences between the two and help set the stage that this module is about projects and not projects (classic). Maybe a table of feature differences/similarities comparing the two would be nice. The rest of the module contents will go over those features and how Projects is better suited for managing your work on GitHub.

**Unit on insights**

I think this is a big enough feature that we need to add a new unit for talking about the insights tab. Here are subsections I think we need to add:
- What are insights and how can they be useful
- Current available charts / historical charts
- Creating and customizing charts

[Here is the docs page for insights](https://docs.github.com/en/issues/planning-and-tracking-with-projects/viewing-insights-from-your-project/about-insights-for-projects)

**Unit on managing your project**

I think we need a unit about managing your project. I don't want this to follow the docs with step-by-step instructions for doing each task, so maybe we can do that for some but then just explain how you can do that for others. Here are the topics I think we can add for this unit:
- Project visibility
- Project access
- Closing / deleting projects
- Adding a project to a repo
- Adding a project to a team

**Comment by camihmerhar** [comment]
Thanks for the feedback @a-a-ron!! I will update and edit the alt text for the images to be more descriptive, add the 2 units you suggested, as well as add API and Actions content to the automation subsection. Let me know if you have any additions!

**Comment by a-a-ron** [comment]
Here is a link to that blog post that we talked about: https://github.blog/2022-11-15-the-journey-of-your-work-has-never-been-clearer/

**Comment by a-a-ron** [comment]
Module was published. Closing out!

**Pull request closed without merging**
